[package]
name = "todo-tui"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "todo"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
ratatui = { workspace = true }
tokio = { workspace = true }
todo-core = { path = "../todo-core" }